/**
 * @file test_ceph.c
 * @author Michal Vasko <mvasko@cesnet.cz>
 * @brief ceph SR DS plugin test
 *
 * @copyright
 * Copyright (c) 2022 Deutsche Telekom AG.
 * Copyright (c) 2022 CESNET, z.s.p.o.
 *
 * This source code is licensed under BSD 3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://opensource.org/licenses/BSD-3-Clause
 */

#include "tconfig.h"

/* augeas SR DS plugin */
#define AUG_TEST_INPUT_FILES AUG_CONFIG_FILES_DIR "/ceph"
#include "srds_augeas.c"
#include "srdsa_init.c"
#include "srdsa_load.c"
#include "srdsa_store.c"
#include "srdsa_common.c"

#include <assert.h>
#include <dlfcn.h>
#include <setjmp.h>
#include <stdarg.h>
#include <unistd.h>

#include <cmocka.h>
#include <libyang/libyang.h>
#include <sysrepo/plugins_datastore.h>

#define AUG_TEST_MODULE "ceph"

static int
setup_f(void **state)
{
    return tsetup_glob(state, AUG_TEST_MODULE, &srpds__, AUG_TEST_INPUT_FILES);
}

static void
test_load(void **state)
{
    struct tstate *st = (struct tstate *)*state;
    char *str;

    assert_int_equal(SR_ERR_OK, st->ds_plg->load_cb(st->mod, SR_DS_STARTUP, NULL, 0, &st->data));
    lyd_print_mem(&str, st->data, LYD_XML, LYD_PRINT_WITHSIBLINGS);

    assert_string_equal(str,
            "<" AUG_TEST_MODULE " xmlns=\"aug:" AUG_TEST_MODULE "\">\n"
            "  <config-file>" AUG_CONFIG_FILES_DIR "/" AUG_TEST_MODULE "</config-file>\n"
            "  <record-list>\n"
            "    <_id>1</_id>\n"
            "    <record>\n"
            "      <record>global</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>fsid</entry>\n"
            "          <value>{UUID}</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>public network</entry>\n"
            "          <value>192.168.0.0/24</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>3</_id>\n"
            "        <entry>\n"
            "          <entry>cluster network</entry>\n"
            "          <value>192.168.0.0/24</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>4</_id>\n"
            "        <entry>\n"
            "          <entry>pid file</entry>\n"
            "          <value>/var/run/ceph/$name.pid</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>5</_id>\n"
            "        <entry>\n"
            "          <entry>max open files</entry>\n"
            "          <value>131072</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>6</_id>\n"
            "        <entry>\n"
            "          <entry>auth cluster required</entry>\n"
            "          <value>cephx</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>7</_id>\n"
            "        <entry>\n"
            "          <entry>auth service required</entry>\n"
            "          <value>cephx</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>8</_id>\n"
            "        <entry>\n"
            "          <entry>auth client required</entry>\n"
            "          <value>cephx</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>9</_id>\n"
            "        <entry>\n"
            "          <entry>cephx require signatures</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>10</_id>\n"
            "        <entry>\n"
            "          <entry>cephx cluster require signatures</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>11</_id>\n"
            "        <entry>\n"
            "          <entry>cephx service require signatures</entry>\n"
            "          <value>false</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>12</_id>\n"
            "        <entry>\n"
            "          <entry>keyring</entry>\n"
            "          <value>/etc/ceph/$cluster.$name.keyring</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>13</_id>\n"
            "        <entry>\n"
            "          <entry>osd pool default size</entry>\n"
            "          <value>3</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>14</_id>\n"
            "        <entry>\n"
            "          <entry>osd pool default min size</entry>\n"
            "          <value>2</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>15</_id>\n"
            "        <entry>\n"
            "          <entry>osd pool default pg num</entry>\n"
            "          <value>128</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>16</_id>\n"
            "        <entry>\n"
            "          <entry>osd pool default pgp num</entry>\n"
            "          <value>128</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>17</_id>\n"
            "        <entry>\n"
            "          <entry>osd pool default crush rule</entry>\n"
            "          <value>0</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>18</_id>\n"
            "        <entry>\n"
            "          <entry>osd crush chooseleaf type</entry>\n"
            "          <value>1</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>19</_id>\n"
            "        <entry>\n"
            "          <entry>log file</entry>\n"
            "          <value>/var/log/ceph/$cluster-$name.log</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>20</_id>\n"
            "        <entry>\n"
            "          <entry>log to syslog</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>21</_id>\n"
            "        <entry>\n"
            "          <entry>ms bind ipv6</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>2</_id>\n"
            "    <record>\n"
            "      <record>mon</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>mon initial members</entry>\n"
            "          <value>mycephhost</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>mon host</entry>\n"
            "          <value>cephhost01,cephhost02</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>3</_id>\n"
            "        <entry>\n"
            "          <entry>mon addr</entry>\n"
            "          <value>192.168.0.101,192.168.0.102</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>4</_id>\n"
            "        <entry>\n"
            "          <entry>mon data</entry>\n"
            "          <value>/var/lib/ceph/mon/$name</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>5</_id>\n"
            "        <entry>\n"
            "          <entry>mon clock drift allowed</entry>\n"
            "          <value>.15</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>6</_id>\n"
            "        <entry>\n"
            "          <entry>mon clock drift warn backoff</entry>\n"
            "          <value>30</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>7</_id>\n"
            "        <entry>\n"
            "          <entry>mon osd full ratio</entry>\n"
            "          <value>.95</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>8</_id>\n"
            "        <entry>\n"
            "          <entry>mon osd nearfull ratio</entry>\n"
            "          <value>.85</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>9</_id>\n"
            "        <entry>\n"
            "          <entry>mon osd down out interval</entry>\n"
            "          <value>600</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>10</_id>\n"
            "        <entry>\n"
            "          <entry>mon osd report timeout</entry>\n"
            "          <value>300</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>11</_id>\n"
            "        <entry>\n"
            "          <entry>debug ms</entry>\n"
            "          <value>1</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>12</_id>\n"
            "        <entry>\n"
            "          <entry>debug mon</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>13</_id>\n"
            "        <entry>\n"
            "          <entry>debug paxos</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>14</_id>\n"
            "        <entry>\n"
            "          <entry>debug auth</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>3</_id>\n"
            "    <record>\n"
            "      <record>mon.alpha</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>alpha</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>mon addr</entry>\n"
            "          <value>192.168.0.10:6789</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>4</_id>\n"
            "    <record>\n"
            "      <record>mon.beta</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>beta</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>mon addr</entry>\n"
            "          <value>192.168.0.11:6789</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>5</_id>\n"
            "    <record>\n"
            "      <record>mon.gamma</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>gamma</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>mon addr</entry>\n"
            "          <value>192.168.0.12:6789</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>6</_id>\n"
            "    <record>\n"
            "      <record>mds</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>keyring</entry>\n"
            "          <value>/var/lib/ceph/mds/$name/keyring</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>mds standby replay</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>3</_id>\n"
            "        <entry>\n"
            "          <entry>debug ms</entry>\n"
            "          <value>1</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>4</_id>\n"
            "        <entry>\n"
            "          <entry>debug mds</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>5</_id>\n"
            "        <entry>\n"
            "          <entry>debug journaler</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>6</_id>\n"
            "        <entry>\n"
            "          <entry>mds cache memory limit</entry>\n"
            "          <value>2G</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>7</_id>\n"
            "    <record>\n"
            "      <record>mds.alpha</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>alpha</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>8</_id>\n"
            "    <record>\n"
            "      <record>mds.beta</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>beta</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>9</_id>\n"
            "    <record>\n"
            "      <record>osd</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>osd data</entry>\n"
            "          <value>/var/lib/ceph/osd/$name</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>osd recovery max active</entry>\n"
            "          <value>3</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>3</_id>\n"
            "        <entry>\n"
            "          <entry>osd max backfills</entry>\n"
            "          <value>5</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>4</_id>\n"
            "        <entry>\n"
            "          <entry>osd max scrubs</entry>\n"
            "          <value>2</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>5</_id>\n"
            "        <entry>\n"
            "          <entry>osd mkfs type</entry>\n"
            "          <value>btrfs</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>6</_id>\n"
            "        <entry>\n"
            "          <entry>osd mount options btrfs</entry>\n"
            "          <value>noatime,nodiratime</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>7</_id>\n"
            "        <entry>\n"
            "          <entry>osd journal</entry>\n"
            "          <value>/var/lib/ceph/osd/$name/journal</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>8</_id>\n"
            "        <entry>\n"
            "          <entry>osd check for log corruption</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>9</_id>\n"
            "        <entry>\n"
            "          <entry>osd journal size</entry>\n"
            "          <value>2048</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>10</_id>\n"
            "        <entry>\n"
            "          <entry>journal dio</entry>\n"
            "          <value>false</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>11</_id>\n"
            "        <entry>\n"
            "          <entry>debug ms</entry>\n"
            "          <value>1</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>12</_id>\n"
            "        <entry>\n"
            "          <entry>debug osd</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>13</_id>\n"
            "        <entry>\n"
            "          <entry>debug filestore</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>14</_id>\n"
            "        <entry>\n"
            "          <entry>debug journal</entry>\n"
            "          <value>20</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>15</_id>\n"
            "        <entry>\n"
            "          <entry>filestore max sync interval</entry>\n"
            "          <value>5</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>16</_id>\n"
            "        <entry>\n"
            "          <entry>filestore btrfs snap</entry>\n"
            "          <value>false</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>17</_id>\n"
            "        <entry>\n"
            "          <entry>filestore flusher</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>18</_id>\n"
            "        <entry>\n"
            "          <entry>filestore queue max ops</entry>\n"
            "          <value>500</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>19</_id>\n"
            "        <entry>\n"
            "          <entry>filestore merge threshold</entry>\n"
            "          <value>-10</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>20</_id>\n"
            "        <entry>\n"
            "          <entry>filestore split multiple</entry>\n"
            "          <value>2</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>21</_id>\n"
            "        <entry>\n"
            "          <entry>filestore op threads</entry>\n"
            "          <value>4</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>22</_id>\n"
            "        <entry>\n"
            "          <entry>osd crush update on start</entry>\n"
            "          <value>false</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>10</_id>\n"
            "    <record>\n"
            "      <record>osd.0</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>delta</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>11</_id>\n"
            "    <record>\n"
            "      <record>osd.1</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>epsilon</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>12</_id>\n"
            "    <record>\n"
            "      <record>osd.2</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>zeta</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>13</_id>\n"
            "    <record>\n"
            "      <record>osd.3</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>eta</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>14</_id>\n"
            "    <record>\n"
            "      <record>client</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>rbd cache</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>rbd cache size</entry>\n"
            "          <value>33554432</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>3</_id>\n"
            "        <entry>\n"
            "          <entry>rbd cache max dirty</entry>\n"
            "          <value>25165824</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>4</_id>\n"
            "        <entry>\n"
            "          <entry>rbd cache target dirty</entry>\n"
            "          <value>16777216</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>5</_id>\n"
            "        <entry>\n"
            "          <entry>rbd cache max dirty age</entry>\n"
            "          <value>1.0</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>6</_id>\n"
            "        <entry>\n"
            "          <entry>rbd cache writethrough until flush</entry>\n"
            "          <value>true</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>7</_id>\n"
            "        <entry>\n"
            "          <entry>admin socket</entry>\n"
            "          <value>/var/run/ceph/$cluster-$type.$id.$pid.$cctid.asok</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "  <record-list>\n"
            "    <_id>15</_id>\n"
            "    <record>\n"
            "      <record>client.radosgw.gateway</record>\n"
            "      <entry-list>\n"
            "        <_id>1</_id>\n"
            "        <entry>\n"
            "          <entry>rgw data</entry>\n"
            "          <value>/var/lib/ceph/radosgw/$name</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>2</_id>\n"
            "        <entry>\n"
            "          <entry>host</entry>\n"
            "          <value>ceph-radosgw</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>3</_id>\n"
            "        <entry>\n"
            "          <entry>keyring</entry>\n"
            "          <value>/etc/ceph/ceph.client.radosgw.keyring</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>4</_id>\n"
            "        <entry>\n"
            "          <entry>rgw socket path</entry>\n"
            "          <value>/var/run/ceph/ceph.radosgw.gateway.fastcgi.sock</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>5</_id>\n"
            "        <entry>\n"
            "          <entry>log file</entry>\n"
            "          <value>/var/log/ceph/client.radosgw.gateway.log</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>6</_id>\n"
            "        <entry>\n"
            "          <entry>rgw print continue</entry>\n"
            "          <value>false</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "      <entry-list>\n"
            "        <_id>7</_id>\n"
            "        <entry>\n"
            "          <entry>rgw dns name</entry>\n"
            "          <value>radosgw.ceph.internal</value>\n"
            "        </entry>\n"
            "      </entry-list>\n"
            "    </record>\n"
            "  </record-list>\n"
            "</" AUG_TEST_MODULE ">\n");
    free(str);
}

static void
test_store_add(void **state)
{
    struct tstate *st = (struct tstate *)*state;
    struct lyd_node *entries, *node;

    /* load current data */
    assert_int_equal(SR_ERR_OK, st->ds_plg->load_cb(st->mod, SR_DS_STARTUP, NULL, 0, &st->data));

    /* add some new list instances */
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='11']/record/entry-list[_id='2']/"
            "entry/entry", "filestore flusher", 0, &entries));
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='11']/record/entry-list[_id='2']/"
            "entry/value", "false", 0, NULL));

    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='6']/record/entry-list[_id='7']/"
            "entry/entry", "host", 0, &entries));
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='6']/record/entry-list[_id='7']/"
            "entry/value", "gama", 0, NULL));
    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='6']/record/entry-list[_id='1']", 0, &node));
    assert_int_equal(LY_SUCCESS, lyd_insert_before(node, entries));

    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='16']/record/record", "mds.omega", 0, &entries));
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='16']/record/entry-list[_id='1']/"
            "entry/entry", "host", 0, NULL));
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='16']/record/entry-list[_id='1']/"
            "entry/value", "omega", 0, NULL));
    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='8']", 0, &node));
    assert_int_equal(LY_SUCCESS, lyd_insert_after(node, entries));

    /* store new data */
    assert_int_equal(SR_ERR_OK, st->ds_plg->store_cb(st->mod, SR_DS_STARTUP, NULL, st->data));

    /* diff */
    assert_int_equal(0, tdiff_files(state,
            "174a175\n"
            "> host=gama\n"
            "197a199,200\n"
            "> [mds.omega]\n"
            "> host=omega\n"
            "325a329\n"
            "> filestore flusher=false\n"));
}

static void
test_store_modify(void **state)
{
    struct tstate *st = (struct tstate *)*state;
    struct lyd_node *entries, *node;

    /* load current data */
    assert_int_equal(SR_ERR_OK, st->ds_plg->load_cb(st->mod, SR_DS_STARTUP, NULL, 0, &st->data));

    /* modify some values */
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='15']/record/record",
            "client.radosgw.gateway.new", LYD_NEW_PATH_UPDATE, NULL));
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='15']/record/entry-list[_id='2']/"
            "entry/value", "ceph-radosgw-update", LYD_NEW_PATH_UPDATE, NULL));
    assert_int_equal(LY_SUCCESS, lyd_new_path(st->data, NULL, "record-list[_id='15']/record/entry-list[_id='6']/"
            "entry/entry", "rgw print update continue", LYD_NEW_PATH_UPDATE, NULL));

    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='14']/record/entry-list[_id='2']", 0, &entries));
    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='14']/record/entry-list[_id='6']", 0, &node));
    assert_int_equal(LY_SUCCESS, lyd_insert_after(node, entries));

    /* store new data */
    assert_int_equal(SR_ERR_OK, st->ds_plg->store_cb(st->mod, SR_DS_STARTUP, NULL, st->data));

    /* diff */
    assert_int_equal(0, tdiff_files(state,
            "339a340,343\n"
            ">     rbd cache max dirty                = 25165824\n"
            ">     rbd cache target dirty             = 16777216\n"
            ">     rbd cache max dirty age            = 1.0\n"
            ">     rbd cache writethrough until flush = true\n"
            "353d356\n"
            "<     rbd cache max dirty                = 25165824\n"
            "361d363\n"
            "<     rbd cache target dirty             = 16777216\n"
            "367d368\n"
            "<     rbd cache max dirty age            = 1.0\n"
            "376d376\n"
            "<     rbd cache writethrough until flush = true\n"
            "384c384\n"
            "< [client.radosgw.gateway]\n"
            "---\n"
            "> [client.radosgw.gateway.new]\n"
            "387c387\n"
            "< host=ceph-radosgw\n"
            "---\n"
            "> host=ceph-radosgw-update\n"
            "391c391\n"
            "< rgw print continue=false\n"
            "---\n"
            "> rgw print update continue=false\n"));
}

static void
test_store_remove(void **state)
{
    struct tstate *st = (struct tstate *)*state;
    struct lyd_node *node;

    /* load current data */
    assert_int_equal(SR_ERR_OK, st->ds_plg->load_cb(st->mod, SR_DS_STARTUP, NULL, 0, &st->data));

    /* remove list values */
    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='7']", 0, &node));
    lyd_free_tree(node);

    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='14']/record/entry-list[_id='4']", 0, &node));
    lyd_free_tree(node);
    assert_int_equal(LY_SUCCESS, lyd_find_path(st->data, "record-list[_id='14']/record/entry-list[_id='5']", 0, &node));
    lyd_free_tree(node);

    /* store new data */
    assert_int_equal(SR_ERR_OK, st->ds_plg->store_cb(st->mod, SR_DS_STARTUP, NULL, st->data));

    /* diff */
    assert_int_equal(0, tdiff_files(state,
            "192,194d191\n"
            "< [mds.alpha]\n"
            "<     host                       = alpha\n"
            "< \n"
            "361d357\n"
            "<     rbd cache target dirty             = 16777216\n"
            "367d362\n"
            "<     rbd cache max dirty age            = 1.0\n"));
}

int
main(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_teardown(test_load, tteardown),
        cmocka_unit_test_teardown(test_store_add, tteardown),
        cmocka_unit_test_teardown(test_store_modify, tteardown),
        cmocka_unit_test_teardown(test_store_remove, tteardown),
    };

    return cmocka_run_group_tests(tests, setup_f, tteardown_glob);
}
